"""Add progress_metadata to JobRecord

Revision ID: 64970cccdab8
Revises: 003_add_signals_table
Create Date: 2026-07-23 09:49:41.044707

"""
from __future__ import annotations

from typing import Sequence, Union

from sqlalchemy.types import Text
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '64970cccdab8'
down_revision: Union[str, Sequence[str], None] = '003_add_signals_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN SET NOT NULL directly.
    # For SQLite, we use batch_alter_table which recreates the table.
    # For Postgres, we use alter_column directly.
    from alembic import context

    bind = context.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    if is_sqlite:
        # SQLite: use batch operations
        with op.batch_alter_table('audit_logs', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=False)

        with op.batch_alter_table('dsar_requests', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=False)

        with op.batch_alter_table('jobs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('progress_metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=False)
            batch_op.alter_column('updated_at',
                       existing_type=sa.DATETIME(),
                       nullable=False)

        with op.batch_alter_table('photo_cache', schema=None) as batch_op:
            batch_op.alter_column('uploaded_at',
                       existing_type=sa.DATETIME(),
                       nullable=False)
            batch_op.alter_column('expires_at',
                       existing_type=sa.DATETIME(),
                       nullable=False)

        with op.batch_alter_table('signals', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=False)

        with op.batch_alter_table('suppression_list', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=False)
    else:
        # Postgres: use regular alter_column
        op.alter_column('audit_logs', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        op.alter_column('dsar_requests', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        op.add_column('jobs', sa.Column('progress_metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
        op.alter_column('jobs', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        op.alter_column('jobs', 'updated_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        op.alter_column('photo_cache', 'uploaded_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        op.alter_column('photo_cache', 'expires_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        op.alter_column('signals', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        op.alter_column('suppression_list', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import context

    bind = context.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    if is_sqlite:
        # SQLite: use batch operations
        with op.batch_alter_table('suppression_list', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=True)

        with op.batch_alter_table('signals', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=True)

        with op.batch_alter_table('photo_cache', schema=None) as batch_op:
            batch_op.alter_column('expires_at',
                       existing_type=sa.DATETIME(),
                       nullable=True)
            batch_op.alter_column('uploaded_at',
                       existing_type=sa.DATETIME(),
                       nullable=True)

        with op.batch_alter_table('jobs', schema=None) as batch_op:
            batch_op.alter_column('updated_at',
                       existing_type=sa.DATETIME(),
                       nullable=True)
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=True)
            batch_op.drop_column('progress_metadata')

        with op.batch_alter_table('dsar_requests', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=True)

        with op.batch_alter_table('audit_logs', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                       existing_type=sa.DATETIME(),
                       nullable=True)
    else:
        # Postgres: use regular alter_column
        op.alter_column('suppression_list', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        op.alter_column('signals', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        op.alter_column('photo_cache', 'expires_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        op.alter_column('photo_cache', 'uploaded_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        op.alter_column('jobs', 'updated_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        op.alter_column('jobs', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        op.drop_column('jobs', 'progress_metadata')
        op.alter_column('dsar_requests', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        op.alter_column('audit_logs', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
    # ### end Alembic commands ###
